# Generated by Django 5.1.3 on 2024-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_about_contact_experience_home_skill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="startData",
            new_name="startDate",
        ),
    ]
