# Generated by Django 5.1.4 on 2025-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_startdata_experience_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
