# Generated by Django 5.1.4 on 2025-07-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_contact_resume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-endDate", "-startDate"]},
        ),
    ]
