# Generated by Django 5.1.4 on 2025-07-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_experience_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["-current", "-endDate", "-startDate"]},
        ),
        migrations.AddField(
            model_name="experience",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
