# Generated by Django 5.1.4 on 2025-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_experience_options_experience_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="recent_skills",
            field=models.TextField(
                blank=True,
                help_text="Enter recent skills separated by commas (e.g., LLMs, Ollama, LangChain)",
                null=True,
            ),
        ),
    ]
